version: '2'

services:
    webserver:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - ./nginx/conf/dev:/etc/nginx/conf.d/:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        depends_on:
            - fish-hub
            - back-fish
            - ia
            - born
            # - http-cors
        networks:
            - fish-hub-network
            - back-fish-network
            - analyze-fish-remork-network
            - born-network
            - video-network

    fish-hub:
        build: ./web-appli
        image: banuyls-biodiversarium-wep-appli-dev
        restart: always
        networks:
            - fish-hub-network
        env_file:
            - ./web-appli/.env.dev
        volumes:
            - "./web-appli:/usr/src/app"

    back-fish:
        build: ./back-fish
        image: banuyls-biodiversarium-back-fish-dev
        restart: always
        networks:
            - back-fish-network
            - analyze-fish-back-network
        volumes:
            - "./back-fish/api:/usr/src/app"

    ia:
        build: ./analyze-fish-remork
        restart: always
        networks:
            - analyze-fish-remork-network
            - analyze-fish-back-network

    born: 
        build: ./biodiversarium-bornfront/biodiversarium-bornfront
        image: banuyls-biodiversarium-born-dev
        restart: always
        networks:
            - born-network
        environment:
            - PORT=80
        volumes:
            - "./biodiversarium-bornfront/biodiversarium-bornfront:/usr/src/app"


    # http-cors:
    #     build: ./biodiversarium-bornfront/video-proxy
    #     restart: always
    #     networks:
    #         - video-network
    #     environment:
    #         - PORT=80
    #         - URL=http://localhost:8080/stream.ogg

networks:
    fish-hub-network:
        external: false

    back-fish-network:
        external: false

    analyze-fish-remork-network:
        external: false

    analyze-fish-back-network:
        external: false

    born-network:
        external: false

    video-network:
        external: false

    default:
        external: false
