version: '3'

services:
    webserver:
        image: nginx:latest
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - ./nginx/conf/dev:/etc/nginx/conf.d/:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        depends_on:
            - fish-hub
            - back-fish
            - ia
        networks:
            - fish-hub-network
            - back-fish-network
            - analyze-fish-remork-network

    fish-hub:
        build: ./web-appli
        restart: always
        networks:
            - fish-hub-network

    back-fish:
        build: ./back-fish
        restart: always
        networks:
            - back-fish-network
            - analyze-fish-back-network

    ia:
        build: ./analyze-fish-remork
        restart: always
        networks:
            - analyze-fish-remork-network
            - analyze-fish-back-network

networks:
    fish-hub-network:
        external: false
    back-fish-network:
        external: false
    analyze-fish-remork-network:
        external: false
    analyze-fish-back-network:
        external: false
    default:
        external: false
