version: "2.5"

services:
    webserver:
        image: nginx:stable-alpine
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - ./nginx/conf/dev:/etc/nginx/conf.d/:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        depends_on:
            - fish-hub
            - back-fish
            - ia
            - born
            - http-cors
        networks:
            - fish-hub-network
            - back-fish-network
            - analyze-fish-network
            - born-network
            - video-network

    fish-hub:
        build:
            context: web-appli/
            target: banuyls-biodiversarium-wep-appli-prod
        restart: always
        networks:
            - fish-hub-network
        environment:
            - REACT_APP_API_URL=""

    back-fish:
        build:
            context: back-fish/
            target: banuyls-biodiversarium-back-fish-prod
        restart: always
        networks:
            - back-fish-network
            - analyze-fish-back-network
        ports: "888:80"

    ia:
        build:
            context: analyze-fish/
        restart: always
        networks:
            - analyze-fish-network
            - analyze-fish-back-network

    born:
        build:
            context: biodiversarium-bornfront/biodiversarium-bornfront/
            target: banuyls-biodiversarium-born-prod
        restart: always
        networks:
            - born-network
        environment:
            - PORT=80
            - REACT_APP_API_URL=""
        ports:
            - "777:80"

    http-cors:
        build:
            context: biodiversarium-bornfront/video-proxy/
        restart: always
        networks:
            - video-network
        environment:
            - PORT=80
            - URL=http://localhost:8080/stream.ogg

networks:
    fish-hub-network:
        external: false

    back-fish-network:
        external: false

    analyze-fish-network:
        external: false

    analyze-fish-back-network:
        external: false

    born-network:
        external: false

    video-network:
        external: false

    default:
        external: false
